name: edscan
version: 1.0.5+5
publish_to: none
description: mobile application facilitate supervision of students in schools.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  connectivity_plus: ^2.3.6+1
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_launch: ^0.3.0
  font_awesome_flutter: ^10.1.0
  get: 4.6.5
  getwidget: ^3.0.1
  hexcolor: ^2.0.7
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  package_info_plus: ^1.4.3+1
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: 2.0.1
  flutter_native_splash: ^2.2.3+1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: "assets/sp.png"
  color: "#ffffff"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
